version: '2'
services:
  web:
    image: devscola/consensus:latest
    container_name: consensus
    build: .
    ports:
      - ${SINATRA_DEFAULT_PORT}:${SINATRA_DEFAULT_PORT}
    volumes:
     - .:/opt/consensus
     - bundle:/usr/local/bundle

    links:
      - selenium
      - mongo
    command: bash -c "bundle install --jobs 3 && bundle exec rake prepare && bundle exec rake"

  selenium:
    image: selenium/standalone-chrome
    ports:
        - "4444:4444"
    container_name: chrome-browser
    logging:
      driver: none

  mongo:
    container_name: "db_mongodb"
    image: mongo:latest
    volumes_from:
        - data
    ports:
        - "27017:27017"
    command: --smallfiles

  data:
    image: mongo:latest
    container_name: "db_mongodb_data"
    volumes:
      - /var/lib/mongo
      - ./setup:/setup
    command: "true"

volumes:
  bundle:
    driver: local
