version: '2'
services:
  web:
    build: .
    ports:
     - "4567:4567"
    volumes:
     - .:/opt/consensus
     - bundle:/usr/local/bundle
    command: bash -c  "bundle install --jobs 3 && bundle exec rake"

volumes:
  bundle:
    driver: local
