version: '2'
services:
  web:
    container_name: consensus
    build: .
    ports:
      - ${SINATRA_DEFAULT_PORT}:${SINATRA_DEFAULT_PORT}
    volumes:
     - .:/opt/consensus
     - bundle:/usr/local/bundle
    links:
      - selenium
    command: bundle exec rake

  selenium:
    image: selenium/standalone-chrome
    ports:
        - "4444:4444"
    container_name: chrome-browser
    logging:
      driver: none

volumes:
  bundle:
    driver: local

